[package]
name = "vocal-synth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.16.0"
simple-eq = { git= "https://github.com/m-hilgendorf/simple-eq" }
rand = "0.8.5"
